class MyError(Exception):
	pass
class LinkError(Exception):
	pass
	